AuthoringFactory = com.dassault_systemes.catia.xapps.dslog.V1.implementations.dslogAuthoringImplPUBLIC
ProposedSolutionFactory = com.dassault_systemes.catia.xapps.dslog.V%1.implementations.dslogProposedSolutionImplPUBLIC
