# ----------------------------------------------------------------------------------------------
# Open V3 protocole getSetting
# ----------------------------------------------------------------------------------------------
# MTX 25:10:06 
# MTX 25:11:03 - FUN165665 is LA FD01, so activateOFWV3 is false
# MTX 26:01:07 - FUN169397 	[Open] 3DExp support of completionOnCAD & filters (v3.0) GA
# RCI 26:02:24 - IR-1499260 [Open] add "ENOUUGC_AP" 
# ----------------------------------------------------------------------------------------------

activateOFWV3 = true
excludedApps = ["ENOUIVC_AP", "ENOUEGC_AP", "SWXCSWK_AP", "ENOUSWC_AP", "ENOUAAC_AP", "ENOV5MA_AP", "ENOUC5C_AP", "ENOUALC_AP", "ENOUCAL_AP", "ENOUCOC_AP", "ENOUPOC_AP", "CATSTI_AP", "GEOUDGC_AP", "GEOUD2C_AP", "CATCYM_AP", "ENOUUGC_AP"]
