
ClassificationAttribute.ImportAttr.InvalidDMS = "Invalid DMSExport -  No attributes to import"
ClassificationAttribute.ImportAttr.predError = "Import attributes modification failure for %s. Predicates cannot be changed."

