AuthoringFactory = com.dassault_systemes.enovia.xapps.dseng.V%1.implementations.dsengAuthoringImpl
IndexedNavigationFactory = com.dassault_systemes.enovia.xapps.dseng.V%1.implementations.dsengIndexedNavigationImpl
EncryptionService =com.dassault_systemes.enovia.xapps.dseng.V%1.implementations.EncryptionService
MultiPositionsItemResponseService =com.dassault_systemes.enovia.xapps.dseng.V%1.implementations.dsengMultiPositionsItemResponseService

VPMReference     = com.dassault_systemes.enovia.xapps.dseng.V%1.implementations.dsengEngItemModelImpl
3DPart           = com.dassault_systemes.enovia.xapps.dseng.V%1.implementations.dsengEngItemPartModelImpl

