AuthoringFactory = com.dassault_systemes.catia.xapps.dspos.V%1.implementations.dsposAuthoringImpl
dsengIndexedNavigationFactory = com.dassault_systemes.enovia.xapps.dseng.V%1.implementations.dsengIndexedNavigationImpl
dsposIndexedNavigationFactory = com.dassault_systemes.catia.xapps.dspos.V%1.implementations.dsposIndexedNavigationImpl

