# Dictionary for ModelerDataParser, with key as the Reader Impl class and Value as the Parser Impl class
com.dassault_systemes.enotransferreader.impl.KernelSerializationReader=com.dassault_systemes.enotransferwriter.impl.KernelSerializationModelerDataParser
