NavigationFactory = com.dassault_systemes.enovia.xapps.dsili.V%1.implementations.dsiliNavigationImpl
AuthoringFactory_v1 = com.dassault_systemes.enovia.xapps.dsili.V%1.implementations.dsiliAuthoringImpl_v1
WebServiceApiProvider = com.dassault_systemes.enovia.xapps.dsili.V%1.implementations.dsiliWebServiceApiProviderImpl
